### ISSUE TITLE
Can we use pytorch channel?

### ISSUE THREAD

**Issue by fecet** [conda-forge/deepspeed-feedstock#17]
### Comment:

I'm not familier with conda-forge, are we restricted to use conda-forge packages? Otherwise can we use pytorch provided from  its own channel so we can also get pytorch-nightly https://anaconda.org/pytorch-nightly/pytorch

**Comment by weiji14** [comment]
Hi @fecet, so sorry for the late reply. I'm assuming that you've managed to install a newer version of Pytorch from conda-forge already (e.g. 2.3.1), so not sure if this issue is still relevant?

In general, we discourage mixing channels because there could be incompatibilities in the builds across different channels (see https://conda-forge.org/docs/user/tipsandtricks/#using-multiple-channels for more information). For the Pytorch library in particular, some of the differences between the `conda-forge` and `pytorch` channel are mentioned at https://github.com/conda-forge/pytorch-cpu-feedstock/issues/218. I'll close this issue for now, but feel free to reopen if you need additional clarification, or comment on the thread in pytorch-cpu-feedstock.
